"""add attribute fields

Revision ID: 1d10f99f50ca
Revises: 
Create Date: 2025-04-14 16:45:54.414326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d10f99f50ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attribute', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_negative', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('base_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attribute', schema=None) as batch_op:
        batch_op.drop_column('base_name')
        batch_op.drop_column('is_negative')
    # ### end Alembic commands ###
